CREATE OR REPLACE TABLE users (
  `username` VARCHAR(40) PRIMARY KEY NOT NULL,
  `mail` VARCHAR(60) UNIQUE NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `firstname` VARCHAR(40) NOT NULL,
  `lastname` VARCHAR(40) NOT NULL
) ENGINE = InnoDB;

CREATE OR REPLACE TABLE news (
  `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `message` LONGTEXT NOT NULL,
  CONSTRAINT `fk_news_users`
    FOREIGN KEY (username) REFERENCES users (username)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;

CREATE OR REPLACE TABLE comments (
  `id` INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `news` INT(11) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (username) REFERENCES users (username)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_comments_news`
    FOREIGN KEY (news) REFERENCES news (id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT 
) ENGINE = InnoDB;